name = "tomjulrep"
uuid = "15584dcc-dffc-470a-840f-7e3d166fd2f1"
authors = ["user "]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = ="3.4"
julia = "1.7.3"
